name: Kickstarter Slack Report

on:
  schedule:
    - cron: "30 * * * *"
  workflow_dispatch:

jobs:
  send-report:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install

      - name: Run Kickstarter report
        run: npm start
        env:
          KICKSTARTER_STATS_URL: ${{ secrets.KICKSTARTER_STATS_URL }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}